name=input("Enter your name : ")
age=input("Enter your age :")
cgpa=input("Enter your cgpa : ")
print("My information ")
print("----------------")
print("Name : "+name)
print("age : "+age)
print("cgpa : "+cgpa)
